language: r
cache: packages

notifications:
  slack: dide-hiv:lZajIW2gCbXMYVgXkp1Bu1ii
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
