void calib_derivs(int * neq, double *t, double *y, double *ydot, double *yout, int *ip);

struct myparms {
    double Nu_1;
    double Nu_2;
    double Nu_3;
    double Nu_4;
    double Nu_5;
    double Nu_6;
    double Rho;
    double Epsilon;
    double Kappa;
    double Gamma;
    double Theta;
    double Omega;
    double p;
    double s_1;
    double s_2;
    double s_3;
    double s_4;
    double s_5;
    double s_6;
    double s_7;
    double Sigma;
    double Delta_1;
    double Delta_2;
    double Delta_3;
    double Delta_4;
    double Delta_5;
    double Alpha_1;
    double Alpha_2;
    double Alpha_3;
    double Alpha_4;
    double Alpha_5;
    double Alpha_6;
    double Alpha_7;
    double Tau_1;
    double Tau_2;
    double Tau_3;
    double Tau_4;
    double Tau_5;
    double Tau_6;
    double Tau_7;
    double Mu;
    double ART_All;
    double ART_500;
    double ART_350;
    double ART_200;
    double Dx_unitCost;
    double Linkage_unitCost;
    double Annual_Care_unitCost;
    double Annual_ART_unitCost;
    double prop_preART_500;
    double prop_preART_350500;
    double prop_preART_250350;
    double prop_preART_200250;
    double prop_preART_100200;
    double prop_preART_50100;
    double prop_preART_50;
    double w1;
    double w2;
    double w3;
    double w4;
    double w5;
    double beta;
    double q;
};

struct myinc {
    double inf[46];
};
